### ISSUE TITLE
Correct speedtest-exporter host-network

### ISSUE THREAD

**Issue by jahanson** [bjw-s/vyos-config#16]
Hey bjw-s, amazing work so far! I appreciate all of your work on home-ops and vyos-config. I came across this and just wanted to let you know. 

https://github.com/bjw-s/vyos-config/blob/478fee54a206cc3685610069b4a324906dbc65fd/config-parts/container.sh#LL80C20-L80C20
Should be `set container name speedtest-exporter allow-host-networks`

**Comment by bjw-s** [comment]
Woah good catch 👍 Thank you for reporting that!
I've fixed it in my latest commit
