### ISSUE TITLE
Potential issue with IoT to Servers firewall

### ISSUE THREAD

**Issue by cbc02009** [bjw-s/vyos-config#42]
I'm not very knowledgeable with firewalls, but it looks like you might accidentally be allowing all traffic from your IoT vlan to your server vlan? 

[This line here](https://github.com/bjw-s/vyos-config/blob/d37e2f1c4a96ba800f69014279ccc636095f0461/config-parts/firewall-ipv4.sh#L354) looks like when it gets reached it just accepts everything?

**Comment by bjw-s** [comment]
Thanks for pointing that out! I think I made (yet another) copy/pasta error when reshuffling some firewall rules. Fixed :)
